### ISSUE TITLE
Crash at runtime / dependency issue after update ?

### ISSUE THREAD

**Issue by jscti** [MFlisar/ComposeDialogs#5]
Hi There

I updated all my dependencies and I'm having a crash when any Dialog opens :  

```
 java.lang.NoSuchMethodError: No static method BasicAlertDialog(Lkotlin/jvm/functions/Function0;Landroidx/compose/ui/Modifier;Landroidx/compose/ui/window/DialogProperties;Lkotlin/jvm/functions/Function2;Landroidx/compose/runtime/Composer;II)V in class Landroidx/compose/material3/AndroidAlertDialog_androidKt; or its super classes (declaration of 'androidx.compose.material3.AndroidAlertDialog_androidKt' appears in com.michaelflisar.composedialogs.core.copied.AlertDialogKt.AlertDialog-ra1Y9rQ(AlertDialog.kt:41)
                                                                                                    	at com.michaelflisar.composedialogs.core.internal.ComposeAlertDialogKt.ComposeAlertDialog(ComposeAlertDialog.kt:195)
                                                                                                    	at com.michaelflisar.composedialogs.core.internal.ComposeAlertDialogKt.ComposeAlertDialog(ComposeAlertDialog.kt:51)
                                                                                                    	at com.michaelflisar.composedialogs.core.DialogKt.Dialog(Dialog.kt:70)
                                                                                                    	at com.michaelflisar.composedialogs.dialogs.list.DialogListKt.DialogList(DialogList.kt:182)
                                                                                                    	at com.michaelflisar.composedialogs.dialogs.list.DialogListKt.DialogList(DialogList.kt:81)
```
...

I don't know if I updated something I shouldn't have or if there is any conflict somehow, do you have an idea ?

My versions right know :  
```
    ext.version_kotlin = '1.9.23'
    ext.version_android_gradle_plugin = '8.6.0'
    ext.version_core = '1.13.1'
    ext.version_compose = '1.7.0'
    ext.version_app_compat = '1.7.0'
    ext.version_kotlin_coroutines = '1.8.1'
    ext.version_lifecycle_extensions = '2.4.1'
    ext.version_moshi = '1.15.1'
    ext.version_room = '2.6.1'
    ext.version_navigation = '2.6.0-alpha02'
    ext.version_retrofit = '2.11.0'
    ext.version_retrofit_coroutines_adapter = "0.9.2"
    ext.version_androidx_preferences = '1.2.1'
    ext.version_work = '2.9.1'
    ext.version_glance = '1.1.0'
    ext.version_mflisar_bom = '2024.03.00'
    ext.billing_version = '7.0.0'
    ext.version_mflisar_compose_dialogs = '1.0.8'
    ext.version_mflisar_compose_preferences = '0.4.7'



buildFeatures {
    compose = true
}

composeOptions {
    kotlinCompilerExtensionVersion = "1.5.12"
}
```

Cleaned-up / rebuilt / gradle gradle cleaned.

Thanks

**Comment by jscti** [comment]
@MFlisar If I downgrade my app "material3" version from 1.3.0 to 1.2.1, it works again.
But I need material3@1.3.0 :/

I don't get why it conflicts

**Comment by MFlisar** [comment]
I do use some `@OptIn` apis here: https://github.com/MFlisar/ComposeDialogs/blob/53435e92b4e56d158cd5fe5354f142d9c45d739d/library/core/src/main/java/com/michaelflisar/composedialogs/core/copied/AlertDialog.kt#L23... those are not binary compatible and that's why you see a crash...

I will make an update this weekend, I probably can remove any non stable api usage in the meantime.

**Comment by jscti** [comment]
Any news on this ? Or workaround ?
Thanks 🙏

**Comment by MFlisar** [comment]
Next version will be a kotlin multiplatform version with compose multiplatform. I checked its current state and sadly, the latest stable version is still using material 1.2.1. I will wait for the next compose multiplatform version before I make a new update.

You can still simply fork this repository, update the dependency, and make the adjustments (there should not be much to do, I assume it's just API adjustments in the copied classes). Then you can even use it directly from your github repository through jitpack...

**Comment by jscti** [comment]
Ok

I just downgraded/rollbacked a few changes to stay on material@1.2 on my side
Still it's strange gradle didn't warn me at compile time in any way and let app crashing at runtime

Thanks

**Comment by KarolCieslar** [comment]
Same issue

**Comment by MFlisar** [comment]
I'm currently rewriting the library to KMP 1.7.0, so it will be updated very soon - next version will be using material3 1.3.0.

**Comment by KarolCieslar** [comment]
Any update?

**Comment by MFlisar** [comment]
Actually I do already use all my libraries in an updated version - I still have to update the readme and write a migration guide and make an official release. I will try to finish that this week.

**Comment by MFlisar** [comment]
[`2.0.0`](https://github.com/MFlisar/ComposeDialogs/releases/tag/2.0.0) is live - it's on maven central now - check out the [setup instructions](https://mflisar.github.io/ComposeDialogs/setup/) to find out how to add the new version.

You probably should also read following:
https://mflisar.github.io/ComposeDialogs/migration/v2/

**Comment by KarolCieslar** [comment]
What about `com.github.MFlisar.ComposePreferences:extension-kotpreferences`? How i can update that?
1.0.0-test10 is not recognized, i cant download it

**Comment by MFlisar** [comment]
The artifact is wrong in the docs - it's just `kotpreferences`. And all is hosted on maven central now (the docs setup page does show that already even for compose preferences).

I've not yet finished writing the docs for composepreferences and because of the new features (especially filtering) all texts have been changed from a composable to a string...

The test release is working and I won't make any big changes anymore, so feel free to try it an use it (I use it in an app as well already) but currently there is no help for migration for you yet...

**Comment by MFlisar** [comment]
issue is redundant now so I close it
